name: C/C++ CI

on:
  push:
    branches:
      - main  # Modify this to match your main branch name
  pull_request:
    branches:
      - main  # Modify this to match your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up CMake
      uses: cmake/setup-cmake@v1

    - name: Configure CMake
      run: cmake -Bbuild -S.

    - name: Build
      run: cmake --build build

    - name: Run tests
      run: cd build && ctest --output-on-failure

